name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Update Release Tags
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update major version tag
        run: |
          # Get the release tag
          TAG=${GITHUB_REF#refs/tags/}
          echo "Release tag: $TAG"
          
          # Extract major version (e.g., v1.2.3 -> v1)
          MAJOR_VERSION=$(echo $TAG | sed -E 's/^v([0-9]+)\..*/v\1/')
          echo "Major version: $MAJOR_VERSION"
          
          # Create or update the major version tag
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -fa $MAJOR_VERSION -m "Update $MAJOR_VERSION to $TAG"
          git push origin $MAJOR_VERSION --force
          
      - name: Validate action
        uses: ./
        with:
          image-urls: |
            hello-world:latest
        continue-on-error: true